import Link from 'next/link';
import AppLayout from '@/components/layout/AppLayout';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Use',
  description: 'Terms of use and disclaimer for the LexAI hackathon demonstration application.',
};

export default function TermsPage() {
  return (
    <AppLayout>
      <div style={{ maxWidth: '800px', margin: '0 auto', paddingBottom: 'var(--space-8)' }}>
        
        {/* Breadcrumb */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)', fontSize: '0.8125rem', color: 'var(--color-text-3)', marginBottom: 'var(--space-4)' }}>
          <Link href="/" style={{ color: 'var(--color-text-3)', textDecoration: 'none' }}>Dashboard</Link>
          <span>/</span>
          <span style={{ color: 'var(--color-text)', fontWeight: 500 }}>Terms of Use</span>
        </div>

        <div style={{ marginBottom: 'var(--space-6)' }}>
          <h1 style={{ fontSize: '1.75rem', fontWeight: 600, color: 'var(--color-text)', letterSpacing: '-0.02em' }}>
            Terms of Use &amp; Legal Disclaimer
          </h1>
          <p style={{ color: 'var(--color-text-2)', marginTop: 'var(--space-1)', fontSize: '0.9375rem' }}>
            Last updated: September 2026 · Hackathon Demonstration Deployment
          </p>
        </div>

        {/* Primary Legal Notice */}
        <div className="notice notice-info" style={{ marginBottom: 'var(--space-6)' }}>
          <span aria-hidden="true">ℹ</span>
          <div>
            <strong>General Informational Purpose Only — Not Legal Advice</strong>
            <p style={{ marginTop: '2px', fontSize: '0.875rem' }}>
              LexAI is an AI-assisted document exploration and literacy tool built for demonstration purposes. <strong>It does not provide legal advice, formal legal opinions, or attorney representation.</strong>
            </p>
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-6)', lineHeight: 1.6, fontSize: '0.9375rem', color: 'var(--color-text)' }}>
          
          <section className="card" style={{ padding: 'var(--space-5)' }}>
            <h2 style={{ fontSize: '1.125rem', fontWeight: 600, marginBottom: 'var(--space-2)', color: 'var(--color-text)' }}>
              1. Nature of the Service
            </h2>
            <p style={{ color: 'var(--color-text-2)', marginBottom: 'var(--space-2)' }}>
              LexAI uses artificial intelligence and natural language processing to assist users in reading, indexing, and summarizing legal documents. 
            </p>
            <p style={{ color: 'var(--color-text-2)' }}>
              The analyses, clause categorizations, risk severity indicators, and checklists generated by LexAI are automated interpretations. No attorney-client relationship is created or implied by accessing or using this service.
            </p>
          </section>

          <section className="card" style={{ padding: 'var(--space-5)' }}>
            <h2 style={{ fontSize: '1.125rem', fontWeight: 600, marginBottom: 'var(--space-2)', color: 'var(--color-text)' }}>
              2. User Responsibility &amp; Verification
            </h2>
            <p style={{ color: 'var(--color-text-2)', marginBottom: 'var(--space-2)' }}>
              You remain solely responsible for your contractual agreements, negotiations, and business decisions:
            </p>
            <ul style={{ paddingLeft: 'var(--space-4)', display: 'flex', flexDirection: 'column', gap: 'var(--space-2)', color: 'var(--color-text-2)' }}>
              <li><strong>Verification:</strong> AI systems can produce inaccurate, incomplete, or hallucinated interpretations. You must independently verify all extracted clauses, dates, and obligations against the original source contract.</li>
              <li><strong>Professional Counsel:</strong> Before executing, modifying, or terminating any legally binding agreement, always consult a qualified licensed attorney in your relevant jurisdiction.</li>
            </ul>
          </section>

          <section className="card" style={{ padding: 'var(--space-5)' }}>
            <h2 style={{ fontSize: '1.125rem', fontWeight: 600, marginBottom: 'var(--space-2)', color: 'var(--color-text)' }}>
              3. Acceptable Use
            </h2>
            <p style={{ color: 'var(--color-text-2)', marginBottom: 'var(--space-2)' }}>
              By using LexAI, you agree to the following conditions:
            </p>
            <ul style={{ paddingLeft: 'var(--space-4)', display: 'flex', flexDirection: 'column', gap: 'var(--space-2)', color: 'var(--color-text-2)' }}>
              <li>You will not upload documents containing malicious code, exploits, or illegal content.</li>
              <li>You will not upload classified, privileged, or highly confidential trade-secret documents to this public demonstration instance.</li>
              <li>You will not attempt to bypass rate limits, probe infrastructure vulnerabilities, or execute adversarial prompt injection attacks intended to compromise the service.</li>
            </ul>
          </section>

          <section className="card" style={{ padding: 'var(--space-5)' }}>
            <h2 style={{ fontSize: '1.125rem', fontWeight: 600, marginBottom: 'var(--space-2)', color: 'var(--color-text)' }}>
              4. Availability &amp; As-Is Warranty Disclaimer
            </h2>
            <p style={{ color: 'var(--color-text-2)' }}>
              LexAI is provided on an &ldquo;AS IS&rdquo; and &ldquo;AS AVAILABLE&rdquo; basis without warranties of any kind, whether express or implied. The developers and contributors disclaim all liability for damages, losses, or disputes arising from reliance on the software&apos;s output or temporary unavailability of the hosted service.
            </p>
          </section>

        </div>
      </div>
    </AppLayout>
  );
}
